# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  testRoutine:
    # Specify the execution environment. 
    docker:
      - image: cimg/base:stable

    working_directory: ~/project

    steps:
      - checkout
      - run:
          name: "Test Routine"
          command: ls -a

workflows:
  testRoutine-workflow:
    jobs:
      - testRoutine
