# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  testRoutine:
    # Specify the execution environment. 
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Test Routine"
          command: "echo Test, Test World!"

workflows:
  testRoutine-workflow:
    jobs:
      - testRoutine

